apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:  
  - dev-portal-deployment.yaml
  - dev-portal-service.yml  

configMapGenerator:
  - name: config-map
    files:
      - appsettings.json